name: Egg-Serve Docker Image CI/CD
on:
  push:
    branches: [feature]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Set Node Variate MYSQL_USER
        run: export MYSQL_USER=${{ secrets.MYSQL_USER }}
      - name: Set Node Variate MYSQL_PASSWORD
        run: export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
      - name: Create Env to Config File
        run: echo "MYSQL_PASSWORD=molimicha12138" >> .env
      - name: Build Image
        run: docker build -t node-serve:latest .
      - name: Login to registry
        run: docker login -u ${{ secrets.IMAGE_USER_NAME }} -p ${{ secrets.IMAGE_USER_PASSWORD }} swr.cn-east-3.myhuaweicloud.com
      - name: Set Docker Tag
        run: docker tag node-serve:latest swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest
      - name: Push Image
        run: docker push swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      # 登录腾讯云服务器并将docker镜像仓库的镜像pull下来后启动新容器
      - name: Deploy
      # 使用appleboy/ssh-action@master完成ssh登录服务器
        uses: appleboy/ssh-action@master
        with:
          host: 124.71.145.91
          username: root
          password: Molimicha12138
          port: 22
          # 登录上服务器后执行的代码步骤（停止旧容器->删除旧容器->删除旧镜像->登录镜像仓库->pull新镜像->利用新镜像启动新容器）
          script: |
            docker stop $(docker ps --filter ancestor=swr.cn-east-3.myhuaweicloud.com/cha/node-serve -q) 2>/dev/null
            docker rm -f $(docker ps -a --filter ancestor=swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest -q) 2>/dev/null
            docker rmi -f $(docker images swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest -q) 2>/dev/null
            docker login -u ${{ secrets.IMAGE_USER_NAME }} -p ${{ secrets.IMAGE_USER_PASSWORD }} swr.cn-east-3.myhuaweicloud.com
            docker pull swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest
            docker run --name node-serve  -d -p 7001:7001 swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest

