name: Egg-Serve Docker Image CI/CD
on:
  push:
    branches: [feature]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Build Image
        run: docker build -t node-serve:latest .
      - name: Login to registry
        run: docker login -u cn-east-3@WU0DRR43BHH0OZI0FNCG -p 02fc58cb6d9b94b96dc3fd7fba31ff6fbbaf79b903d59399a2dfe3b3ce315b5f swr.cn-east-3.myhuaweicloud.com
      - name: Push Image
        run: docker push node-serve:latest
