name: Egg-Serve Docker Image CI/CD
on:
  push:
    branches: [feature]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Build Image
        run: docker build -t node-serve:latest .
      - name: Login to registry
        run: docker login -u ${{ secrets.IMAGE_USER_NAME }} -p ${{IMAGE_USER_PASSWORD}} swr.cn-east-3.myhuaweicloud.com
      - name: Set Docker Tag
        run: docker tag node-serve:latest swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest
      - name: Push Image
        run: docker push swr.cn-east-3.myhuaweicloud.com/cha/node-serve:latest
        
